[wokwi]
version = 1
firmware = "main_arduino/main_arduino.ino"
elf = "build/arduino.avr.uno/main_arduino.ino.elf"

[[pins]]
name = "PWMA"
x = 100
y = 50
analog = true

[[pins]]
name = "Ultrasonic"
x = 150
y = 100